### ISSUE TITLE
[subscriptions] custom onConnect

### ISSUE THREAD

**Issue by AndreMaz** [moleculerjs/moleculer-apollo-server#104]
I think I found a small issue when passing a custom `onConnect` middleware. The default `onConnect` looks like this
https://github.com/moleculerjs/moleculer-apollo-server/blob/2463499c8c0a0f6c65e35f59f01195bc3b60ea59/src/service.js#L656-L659

which simply calls the `ws` action to set the params
https://github.com/moleculerjs/moleculer-apollo-server/blob/2463499c8c0a0f6c65e35f59f01195bc3b60ea59/src/service.js#L32-L50

However, when passing custom `onConnect` I can't access the `ws` action because the `this` points to a `SubscriptionServer` instead of moleculer `Service`.

To solve it I've added the following lines in the `created()` function:

```js
if (_.isFunction(mixinOptions.serverOptions.subscriptions.onConnect)){
    mixinOptions.serverOptions.subscriptions.onConnect = mixinOptions.serverOptions.subscriptions.onConnect.bind(this)
}
```

@Hugome can you please check if my approach is correct?

**Comment by icebob** [comment]
Maybe it's related https://github.com/moleculerjs/moleculer-apollo-server/issues/75

**Comment by AndreMaz** [comment]
You're right, it's definitely related. @shawnmcknight do you have any thoughts on this?

**Comment by AndreMaz** [comment]
Note: with this approach we continue to have access to the `SubscriptionServer`
![image](https://user-images.githubusercontent.com/9802754/147547709-4946ecdc-71c7-4ceb-a6b5-caa205b527b7.png)

**Comment by AndreMaz** [comment]
@Hugome @shawnmcknight sorry to bother you again but do you have any thoughts about this?
