### ISSUE TITLE
Use with dataloader

### ISSUE THREAD

**Issue by shawnmcknight** [moleculerjs/moleculer-apollo-server#13]
[dataloader](https://www.npmjs.com/package/dataloader) is a popular methodology for GraphQL to aggregate and batch requests in order to limit N+1 problems.  It is even discussed in Apollo's [documentation](https://www.apollographql.com/docs/graphql-tools/connectors.html#dataloader).

I could not figure out a way to utilize a dataloader using the existing resolver API in moleculer-apollo-server.  I've spent some time creating a prototype of a potential way to allow use of them in a [fork](https://github.com/shawnmcknight/moleculer-apollo-server/tree/dataloader) of the repo ([compare](https://github.com/moleculerjs/moleculer-apollo-server/compare/master...shawnmcknight:dataloader)).

The approach I am taking is summarized as follows:
I've augmented the resolver definition to allow for providing a `dataLoader` object property.  That object has 4 parameters: `actionParam`, `rootParam`, optional `isArray`, and optional `arrayObjectParam`.
* `rootParam` defines the property name from the root/parent object that will be the basis for the dataloader call
* `actionParam` defines the parameter name to use to pass the batched `rootParam` values in the moleculer action call
* `isArray` defines the `rootParam` value as an array which should be iterated.  If this is true, the dataloader will be called once for each value in the array rather than for the root parameter's value as a whole
* `arrayObjectParam` is used when the array contains objects and an object's property value should be passed to the `dataLoader`

For example, the existing example repo has this `resolvers` definition in the `posts` service:
```js
author: {
  action: 'users.resolve',
  rootParams: {
    author: 'id',
  },
},
voters: {
  action: 'users.resolve',
  rootParams: {
    voters: 'id',
  },
},
```

With the dataloader API in place, that same example looks like this:
```js
author: {
  action: 'users.resolve',
  dataLoader: { actionParam: 'id', rootParam: 'author' },
},
voters: {
  action: 'users.resolve',
  dataLoader: { actionParam: 'id', rootParam: 'voters', isArray: true },
},
```

My prototype needs a little more polish, but before I invest too much time going down this path, I'd like to gauge whether there is interest in adding this feature to moleculer-apollo-server.  I have a couple questions:
1. Are you interested in allowing dataloaders to be utilized by moleculer-apollo-server?
2. If yes, do you like the path I am heading down?  If so, I can finalize things and submit a PR.
3. If no to either of the above then is there another path that you'd like explored?

I'm definitely willing to tweak things as necessary.  I think this would be a really useful feature.  Thanks!

**Comment by icebob** [comment]
I think it would be a great feature. Can we avoid to use `isArray` and `arrayObjectParam` params and somehow detect them?
Another question: what about with performance? As I see you change the resolve function and use dataloader for every resolver. Does it affect the performance?

**Comment by shawnmcknight** [comment]
> Can we avoid to use `isArray` and `arrayObjectParam` params and somehow detect them?

`isArray`: I had toyed with not including this and just treating it as multiple calls to the `load()` function if it was an array always.  My only concern was with a scenario where the action was expecting an array to be passed instead of a scalar.  In that case, the consumer might want to treat it as a single entity to pass to the `load()` function rather than passing each individual element.  That could be an edge case though, and maybe being opinionated on array utilization would be better.  I'll adjust my code to detect if the parameter's value is an array and behave accordingly if it is.  We can always adjust behavior for the array value that shouldn't be iterated later if a use case arises.

`arrayObjectParam`: After thinking this one through a little more, I don't think this logic is necessary at all.  If a `root` contains an array of objects, it's likely that the resolver function would be working with those objects directly rather than ever using a DataLoader instance.  I didn't have a known use case for it and I was trying to plan ahead a bit, but I think the concept can be eliminated entirely.

> Another question: what about with performance? As I see you change the resolve function and use dataloader for every resolver. Does it affect the performance?

If `def.dataLoader` is not specified, it should simply fall back to the original behavior where the resolver function simply calls the moleculer action directly.  Consumers not specifying the `dataLoader` parameter should see no impact at all.

For consumers specifying `dataLoader`, the idea is that the dataloader should have a significant improvement to performance.  The `load()` function itself has a very minimal footprint and it would reduce the number of moleculer action calls (and presumably database accesses - which is where the real value is) significantly.  When testing the example for posts/users I shrunk the footprint from 10 calls to `user.resolve` to `1`. `users.resolve` isn't optimized to perform an aggregate query, but even without further optimization on that I went from 12 database reads to 5.  With an actual database backing the function (instead of a json sample) that could drop from 12 DB queries to 1.

**Comment by shawnmcknight** [comment]
One other potential option is for the `dataLoader` param to become a Boolean, and piggyback on the existing `rootParams` structure.  The one important thing there is that the nature of dataloader is such that only one value can be passed to the `load()` function, so specifying multiple `rootParams` wouldn't make sense.  I could simply use the first key/value specified in the `rootParams` and ignore any others.  I'll play around with that for simplicity's sake and it can be adjusted if that doesn't make sense.

**Comment by icebob** [comment]
Ok, it sounds good!
