### ISSUE TITLE
Enum Internal Values

### ISSUE THREAD

**Issue by shawnmcknight** [moleculerjs/moleculer-apollo-server#18]
I'm looking to implement a solution to handle Enums with internal value representations (see https://www.apollographql.com/docs/graphql-tools/scalars#internal-values for details).

Currently, I can make this work with moleculer-apollo-server if I define the enumeration's resolver at the global level -- that is, if I define it in the `resolvers` property of the `ApolloService` mixin.  However, this doesn't really feel like an appropriate place to define the enumeration's resolver if the  parent type of the enumeration is defined at the service level.

As an example, consider a service with the following:

```js
settings: {
  graphql: {
    type: `
      """
      Workspace entity
      """
      type Workspace {
        _id: ID!
        name: String!
        environment: WorkspaceEnvironment!
      }
      """
      Workspace Environment Enumerations
      """
      enum WorkspaceEnvironment {
        PRODUCTION
        STAGING
        QA
        DEVELOPMENT
      }
    `,
  },
},
```

I'd like to associate a resolver with `WorkspaceEnvironment` as such:
```js
WorkspaceEnvironment: {
  PRODUCTION: '1',
  STAGING: '2',
  QA: '3',
  DEVELOPMENT: '4',
},
```

If I specify this resolver in the `ApolloService` mixin options, everything works as I expect.  An internal representation of `1` is converted to a enum of `PRODUCTION`, a `2` is converted to `STAGING`, etc.  However, this means locating my enumeration's resolver in the global definition rather than in the service definition which is not really ideal.  However, the service's `resolvers` settings are really intended to specify the resolvers for properties within a type (e.g. if I needed a child resolver for another property in `Workspace`).

I feel like an update to handle this is rather trivial, and I'm happy to do it, but I'm looking for some guidance on how the API should function.  So, ultimately the goal is to allow for a resolver to be specified that surfaces to the global level rather than being a child resolver of a parent -- similar to how the `query` and `mutation` resolvers surface to the global level when specified in the `action` definitions.

I've looked for ways to potentially hook into the existing API and nothing is jumping out at me.  I also tried to figure out if there was a way to specify this resolution in the gql string, but if there is a way I can't find it.  As a workaround, the resolvers can be specified globally, but I think it would be best if they could be located in the service where the `Enum` was defined.

**Comment by icebob** [comment]
Maybe I don't understand the problem, but what is the problem if you define the enum & resolver in the service?

**Comment by shawnmcknight** [comment]
> Maybe I don't understand the problem, but what is the problem if you define the enum & resolver in the service?

Defining the enum in the service is fine.  The problem is that there doesn't appear to be a workable way to define the resolver there as well.  At present, the resolvers that get defined in a service are intended to be bound to an action.  For enum resolvers, Apollo lets you specify an object as the resolver which converts the enum external values to the internal representation like:

```js
WorkspaceEnvironment: {
  PRODUCTION: '1',
  STAGING: '2',
  QA: '3',
  DEVELOPMENT: '4',
},
```

In the service's resolvers, if you specify something like:
```js
resolvers: {
  Workspace: {
    environment: {
      PRODUCTION: '1',
      STAGING: '2',
      QA: '3',
      DEVELOPMENT: '4',
    },
  },
},
```
there will be two issues.  The first is a pretty easy solve -- the API is currently expecting a resolver that is an object to be a wrapper for an action definition.  That can be solved by making the API a little more flexible (which I played around with so I could get past that block).  The second issue is a harder solve and appears to be the way Apollo works.  You can't specify the enum resolver object as a child resolver in the context of its parent.  Basically the call to `makeExecutableSchema` passes something like this (working off memory, I can dredge up the exact details if necessary) as the `resolvers` property:
```js
Workspace: {
  environment: {
    PRODUCTION: '1',
    STAGING: '2',
    QA: '3',
    DEVELOPMENT: '4',
  },
},
```
However, Apollo does nothing with the resolver like this.  It basically throws it away.  Apollo actually wants a resolver tied to the specific enum name like this:
```js
WorkspaceEnvironment: {
  PRODUCTION: '1',
  STAGING: '2',
  QA: '3',
  DEVELOPMENT: '4',
},
```
This is why specifying the resolver definition as the global level for the `ApolloService` mixin works -- the resolver gets passed to Apollo in that manner and everything works perfectly.  No child resolver is needed.

I can probably whip up a more concrete example if it helps.  I'm definitely open to other avenues if you think I'm missing something, but it appears to be that Apollo expects resolvers of this type to be treated more like a custom scalar than a child resolver.

Thanks!

**Comment by shawnmcknight** [comment]
I've modified the full example in this repo to add a `UserType` enumeration to the user data.  See compare [here](https://github.com/moleculerjs/moleculer-apollo-server/compare/master...shawnmcknight:enum-example).

As you can see, the type is represented by an integer in the data (internal representation) but the GraphQL Enum is using full words.  With the enumeration resolver being supplied in the global `resolvers` property passed to the `ApolloService` mixin, this works exactly as expected.  The internal integers are converted to the external enumerated types:
![image](https://user-images.githubusercontent.com/4583869/55091203-c4da6e80-5086-11e9-940f-6db8826a1a7e.png)

However, by locating the enum resolver in the global definition, there is now a separation of the resolver and the enumeration definition.  The enumeration definition really belongs with the user service because its a type of user.  Ideally, the resolver would then be located in the same place.  Unfortunately, I don't think there is a way to have Apollo work with this resolver as a child of the `User` resolver -- it has to be a global resolver.

I've created a sample concept repo [here](https://github.com/moleculerjs/moleculer-apollo-server/compare/master...shawnmcknight:enum-desired).  This moves the resolver out of the global definition and into the service as a property `globalResolvers`.  The expectation would be that those resolvers would get added to the global resolvers definition passed to `makeExecutableSchema`.

This is just an initial thought.  Definitely open to other ideas or if I'm missing another existing way to do it, I'm fine with that too.  Let me know if I can add any other information.

Thanks!

**Comment by icebob** [comment]
Thanks the examples. Now it's better to understand your problem. I will be thinking on it.

**Comment by icebob** [comment]
@shawnmcknight I've tried what you would like (I think). Move enum resolver to the service and it works: https://github.com/moleculerjs/moleculer-apollo-server/commit/bc0800f7ffa9face43b68264f6b0451d33ec92ad#diff-fea519310c42386ad7fed3e495b45a60

![image](https://user-images.githubusercontent.com/306521/55261173-83a2b400-526a-11e9-93a4-55dc98a73346.png)
or have I missed something?

**Comment by shawnmcknight** [comment]
OK - I was very confused at first, but now realize why my initial tests of this same syntax attempt didn't work, but it did work when you did it.

The example repo I created did not match my real-world attempt _exactly_.  There was a key difference --my internal values in the real world were strings and the internal values in my example repo were numbers.  If the internal value is a string, it actually gets hung up on this line:
https://github.com/moleculerjs/moleculer-apollo-server/blob/master/src/service.js#L66

If the resolver is
```js
UserType: {
	ADMIN: "1",
	PUBLISHER: "2",
	READER: "3"
}
```
then it tries to create resolvers bound to actions with names "1", "2", and "3" (which obviously don't exist).  It therefore doesn't convert the internal representation to the external representation.

Sorry that I didn't catch that distinction originally.  Things do seem to work fine if the internal value is not a string.

**Comment by shawnmcknight** [comment]
I created a real [quick sample](https://github.com/moleculerjs/moleculer-apollo-server/compare/master...shawnmcknight:enum-string) of that same repo, converting the internal values to strings to illustrate.

**Comment by icebob** [comment]
Ohh, I see. So the string values conflict with action name resolvers.

**Comment by icebob** [comment]
It means we have two options:

1. option
Drop shorthand action resolver
```js
resolvers: {
	Post: {
		author: "user.get"
	}
}
```
and use always object definition as:
```js
resolvers: {
	Post: {
		author: {
			action: "users.resolve",
			rootParams: {
				"author": "id"
			}
		}
	}
}
```

2. option
Define static enum values in object definition as `value`:
```js
resolvers: {
	UserType: {
		ADMIN: { value: "1" },
		PUBLISHER: { value: "2" },
		READER: { value: "3" }
	}
}
```

What do you think?

**Comment by shawnmcknight** [comment]
> **1) option**
> Drop shorthand action resolver (I don't know it is a relevant feature. Mostly need to define `rootParams`, too)

I agree this doesn't seem relevant.  I struggle to come up with a use case where you'd have a child resolver that you don't need to pass some of the parent's properties to.  If there is a use case, it seems to be an edge case that can still be solved using the object syntax and not providing parameters.  It does not seem to be beneficial enough to keep around.

I'd vote for eliminating the shorthand unless there's a non-edge case I'm not thinking of that makes it really worthwhile.

**Comment by icebob** [comment]
I agree. Could you help and create a fix PR?
