### ISSUE TITLE
moleculer-apollo-server is not found on npmjs.com

### ISSUE THREAD

**Issue by ts0307** [moleculerjs/moleculer-apollo-server#2]

**Comment by corpetty** [comment]
any update to the release estimate for this?

**Comment by icebob** [comment]
After #24

**Comment by icebob** [comment]
@mapoio please transfer the ownership of [moleculer-apollo-server](https://www.npmjs.com/package/moleculer-apollo-server) project on NPM. My NPM username is "icebob". Thanks in advance.

**Comment by mapoio** [comment]
I'm so sorry for that. The ownership is "icebob" now! @icebob

Icebob <notifications@github.com>于2019年7月9日 周二15:19写道：

**Comment by icebob** [comment]
Thank you @mapoio

**Comment by mapoio** [comment]
The ownership transfer need CLI. But my laptop is not by my side. I will transfer owner permissions tomorrow. I  ❤️ the package, it's awesome! @icebob

**Comment by timsayshey** [comment]
Looks like this is still being transferred. Any idea when we will be able to get this package from npm?

**Comment by AndreMaz** [comment]
After https://github.com/moleculerjs/moleculer-apollo-server/issues/24. Any help would be highly appreciated 😉
