### ISSUE TITLE
Ability to create multiple mutations per action

### ISSUE THREAD

**Issue by majest** [moleculerjs/moleculer-apollo-server#20]
One feature it would be great to have is the ability to define multiple mutations for a single action. I use moleculer-db-adapter-mongo that creates endpoints  like: insert, get.. etc. I've noticed if create insert action and add graphql it will be happy to apply the logic from the handler provided by the mongo adapter

```
actions: {
    insert: {
	graphql: {
	    mutation: `
                insertSchedule(
		  entity: ScheduleInput
		): Schedule`
        }
    }
}
```

This works. However, insert has an option to provide both entity and entities (array of inputs). the result would be array of Schedule. If I add insertSchedules like this:

```
actions: {
    insert: {
	graphql: {
	    mutation: `
                insertSchedule(
		  entity: ScheduleInput
		): Schedule

                 insertSchedules(
		  entities: [ScheduleInput]
		): [Schedule]
            `
        }
    }
}
```

It will create the required scheme but it will fail to resolve to insert.

**Comment by icebob** [comment]
Good idea.

**Comment by shawnmcknight** [comment]
@majest Just out of curiosity, have you tried defining a single mutation that accepts/returns an array and passing a single instance in?  I know in my testing of queries, I can specify an array but pass a single value in and Apollo is converting it to an array under the covers.  This lets me achieve a similar scenario to what you're describing but on the query side.  If that works for mutations, it might solve your specific scenario as well, although there are probably other use cases for tying multiple queries/mutations/subscriptions to the same action.

**Comment by majest** [comment]
@shawnmcknight I tried that but no, If you define the output as [Schedule] It expects exactly that. I can do:

```
mutation: `insertSchedule(entity: ScheduleInput, entities: [ScheduleInput]): Schedule`
```

which kinda works because I can pass both entities and entity, it will work in both cases but it will return the valid object only if it matches Schedule, not [Schedule] which what you get when saving many.

```
  "data": {
    "insertSchedule": {
      "_id": null
    }
  },
```

**Comment by majest** [comment]
https://github.com/moleculerjs/moleculer-apollo-server/pull/21
