### ISSUE TITLE
Need help to write unit tests

### ISSUE THREAD

**Issue by icebob** [moleculerjs/moleculer-apollo-server#24]
Hi,

I need help to write unit test to cover all source files. After that, I can publish the package on NPM. Is there somebody to help writing unit test with Jest?

Thanks in advance!

Icebob

**Comment by shawnmcknight** [comment]
It will be great if someone tackles this sooner, but my team is currently converting our API to moleculer and specifically, moleculer-apollo-server.  One of the tasks I've assigned out to my team for the upcoming quarter is to help ensure this repo can get released to npm so we're not running unreleased software in production.

I don't know where exactly it will fit on schedules, but it'll definitely get on there somewhere.  As I mentioned, it'd be awesome if someone else can work on this beforehand, but if push comes to shove we'll get it done.

**Comment by icebob** [comment]
I will create a skeleton for unit tests and maybe cover the service file, at least. Maybe in 1-2 weeks.
