### ISSUE TITLE
Proposal: Implement Prettier code formatter

### ISSUE THREAD

**Issue by shawnmcknight** [moleculerjs/moleculer-apollo-server#25]
[Prettier](https://prettier.io/) is an opinionated code formatter that goes above and beyond what eslint does.  I've found that it makes developing on a shared repo much easier since it takes the guesswork out of the repo's formatting rules.  It [sells itsel](https://prettier.io/docs/en/why-prettier.html)f a lot better than I could.

Anyway, this is a proposal to add prettier to this repo (and if it works out well, extending to other moleculer repos would make sense as well).  I've got a forked branch where I implemented it, integrated it with eslint, and had it fix every issue it detected (as well as some previously unresolved eslint issues).

I've been using prettier on my internal team for a couple years now and I think it's been a huge benefit.  If you think it's a good idea to add here, I'll go ahead and do a PR for the [branch I created](https://github.com/moleculerjs/moleculer-apollo-server/compare/master...shawnmcknight:prettier).

**Comment by icebob** [comment]
Good idea. By the way, I've some doubts about prettier because maybe it can generate less readable codes. However, we can try it here in this repo, at first. So please make a PR :)

**Comment by shawnmcknight** [comment]
> Good idea. By the way, I've some doubts about prettier because maybe it can generate less readable codes. However, we can try it here in this repo, at first. So please make a PR :)

So I've got a few years with prettier under my belt now, and here's what I can say about it:
I probably _like_ what it does 90% of the time.  I'm _okay_ with what it does 9% of the time.  1% of the time I _hate_ it.  But, it saves me so much time and energy in thinking about formatting that any time it does something I don't agree with, I view it as a worthwhile trade off.  Probably the quote from their site that most resonates with me is this one:

>>> We want to free mental threads and end discussions around style. While sometimes fruitful, these discussions are for the most part wasteful.

By just letting eslint/prettier reformat my code, I expend no effort around trying to optimize it to be "pretty" and end up being much more effective in actually creating code.

Anyway, no need to evangelize too much about it.  We can trial it here and if it works out well we can go ahead and turn it on elsewhere.  If it doesn't work out, we'll turn it off.  I've put up a PR.

**Comment by icebob** [comment]
You are right, thanks for sharing your experiences with prettier. I will try it in this repo and check the results.
