### ISSUE TITLE
Multiple mutation syntax prevents structured formatting

### ISSUE THREAD

**Issue by shawnmcknight** [moleculerjs/moleculer-apollo-server#27]
#21 Opened up the ability to bind multiple mutations to the same action.  However, because this is based on a newline defining the breakpoint between mutations, it prevents using the syntax added in #19 for formatting the definition using newlines.  For example:

```js
graphql: {
  mutation: `
    workspaceCreate(
      input: WorkspaceCreateInput!
    ): Workspace
  `,
},
```
will not work because the line breaks are assuming this to be multiple mutations instead of a single mutation definition.

I'd like to propose an alternate way of solving the multiple mutations.  Rather than combining multiple mutations together as concatenations broken by newline, how about specifying each unique mutation as an item in an array?  So rather than this:

```js
graphql: {
  mutation: `
    insertSchedule(entity: ScheduleInput): Schedule
    insertSchedules(entities: [ScheduleInput]): [Schedule]
  `
  },
},
```
we could do:
```js
graphql: {
  mutation: [
    "insertSchedule(entity: ScheduleInput): Schedule",
    "insertSchedules(entities: [ScheduleInput]): [Schedule]",
  ],
},
```

This format could also potentially extend to the other definitions (e.g. `typeDefs`, `enum`, etc.) to allow multiples to be defined a little more cleanly.  As it currently stands, I've been creating individual type definitions in separate files, importing them, and then concatenating them together with templated strings.  It might be a nicer API if we allowed those to just be treated as `string | string[]` and join them together during schema construction.

I can work on a PR if this sounds like a reasonable approach or potentially do something if some alternative ideas are proposed.

**Comment by icebob** [comment]
I prefer the string array solution. Please make a PR.

**Comment by majest** [comment]
Yes, definitely a lot cleaner then trying to parse the string
