### ISSUE TITLE
Subscription Support?

### ISSUE THREAD

**Issue by duongdev** [moleculerjs/moleculer-apollo-server#3]
Do you have any plans to support Apollo Server subscription?

**Comment by snnsnn** [comment]
I thought these links might be helpful. I would like to help with coding but these codes are way over my head.

https://www.apollographql.com/docs/graphql-subscriptions/
https://www.apollographql.com/docs/apollo-server/features/subscriptions.html

These are official repos related to subscription implementation:
https://github.com/apollographql/graphql-subscriptions
https://github.com/apollographql/subscriptions-transport-ws

Apollo Server has `installSubscriptionHandlers` https://github.com/apollographql/apollo-server/blob/ad4240295469821c24aaf2f1032b12882dd3b6f9/packages/apollo-server-core/src/ApolloServer.ts#L401 endpoint for convenience which is used for express and hopi implementations. Here is the related doc [https://www.apollographql.com/docs/apollo-server/v2/features/subscriptions.html#middleware](https://www.apollographql.com/docs/apollo-server/v2/features/subscriptions.html#middleware)

**Comment by icebob** [comment]
Thanks @snnsnn, I will check it. Could somebody create a client-side subscription example which works with the common Apollo Server and I can use it during development?

**Comment by ts0307** [comment]
@icebob 
[https://github.com/Akryum/vue-apollo-example](https://github.com/Akryum/vue-apollo-example)
This is an example of apollo client, including query mutation and subscription.

[https://github.com/Akryum/apollo-server-example](https://github.com/Akryum/apollo-server-example)
This is its server.

wish it is helpful

**Comment by duongdev** [comment]
@icebob @Hugome you guys could you add subscription examples?

**Comment by icebob** [comment]
There is two examples in `examples` folder and @Hugome updated them with subscriptions.
