### ISSUE TITLE
whitelist in routeOptions

### ISSUE THREAD

**Issue by arturgrabowskitb** [moleculerjs/moleculer-apollo-server#33]
I'm trying to implement authentication, added authorization:true to routeOptions but since everything is going through authorize method I need to whitelist "users.login" service. This won't work. Am I missing something here?

```
routeOptions: {
	path: "/graphql",
	whitelist: [
	      "users.login"
	],
	cors: true,
	mappingPolicy: "restrict",
	authorization: true,
},
```

**Comment by shawnmcknight** [comment]
The `whitelist` option should only be necessary if you wish to expose an action using REST conventions.  Your `authorization` method isn't shown here, but I'm assuming you are trying to call the `users.login` action from that method?  You should be able to do that without using the whitelist.

In our implementation of the gateway, we're using the `authentication` hook, but the behavior between `authenticate` and `authorize` is not much different.  Within our `authenticate` method we're calling a non-whitelisted action.

Can you explain your issue in a little more detail?

**Comment by arturgrabowskitb** [comment]
Thanks for quick response. My (changed from authorize to) authenticate methods looks like this:

```
methods: {
		authenticate(ctx, route, req, res) {
			// Read the token from header
			let auth = req.headers["authorization"];
			if (auth && auth.startsWith("Bearer")) {
				// validate token
			} else {
				// No token
				return Promise.reject(new E.UnAuthorizedError(E.ERR_NO_TOKEN));
			}
		}
	}
```

My "user.login" action looks like this: 

```
login: {
	graphql: {
		mutation: [
			gql`loginUser(user: UserAuthInput): UserToken`
		]
	},
        async handler(ctx) {
           // find user and return token
        }
}
```
Route Options:
```
			routeOptions: {
				path: "/graphql",
				whitelist: [
					"users.login"
				],
				cors: true,
				mappingPolicy: "restrict",
				authentication: true,
			},
```

However, you did point me in the right direction. Should I authenticate directly from authenticate method? I've got the parameters under `req.body`

**Comment by icebob** [comment]
Yes, you should authenticate (with calling `users.login`) in `authenticate` hook.

**Comment by icebob** [comment]
Some example which maybe helps you: https://github.com/icebob/kantab/blob/master/backend/services/api.service.js#L214-L250

**Comment by arturgrabowskitb** [comment]
This helped a lot. Thank you!
