### ISSUE TITLE
$services.changed events is not used to regenerate graphql

### ISSUE THREAD

**Issue by mailaneel** [moleculerjs/moleculer-apollo-server#37]
events object is getting completely replaced

https://github.com/moleculerjs/moleculer-apollo-server/blob/dfc23c20b4c8d4efe02442c7e901ed3ae7efd319/src/service.js#L556

**should be**
```js
serviceSchema.events = {
	...(serviceSchema.events || {}),
	[mixinOptions.subscriptionEventName](event) {
		this.pubsub.publish(event.tag, event.payload);
	},
};
```

**Comment by mailaneel** [comment]
Also noticed schema does not update to reflect new changes. It show the old schema

**Comment by shawnmcknight** [comment]
@mailaneel Good catch.  I had seen this happen once before but it had not reoccurred.  We haven't seen it because we redeploy all of our services together, but I'm betting we would run into a timing issue and see it again later.  I've created #38 to address this.

**Comment by mailaneel** [comment]
thanks @shawnmcknight
