### ISSUE TITLE
Cannot delete property 'ctx' of MoleculerClientError

### ISSUE THREAD

**Issue by deman4ik** [moleculerjs/moleculer-apollo-server#50]
After throwing any error from action I get

```json
{
  "errors": [
    {
      "message": "Cannot delete property 'ctx' of MoleculerClientError: Invalid role",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "nodesList"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot delete property 'ctx' of MoleculerClientError: Invalid role",
            "    at .../node_modules/moleculer-apollo-server/src/service.js:121:8"
          ]
        }
      }
    }
  ],
  "data": null,
  "extensions": {}
}
```

**Comment by shawnmcknight** [comment]
Line 121 of `service.js` is attempting to delete the `ctx` property from the error object:
```
if (err && err.ctx) {
  delete err.ctx; // Avoid circular JSON
}
```

The error seems to be thrown by the interpreter here, but a Google search hasn't turned up anything for me regarding an "Invalid role" message, so I'm not sure what's causing that.

Running the example posts service with the `nullIfError` flag set to false emits the proper error and does not run into this `TypeError`.  In our environment we throw errors regularly and don't run into this.

Can you provide more information / code sample of what service looks like?  What node version are you running?
