### ISSUE TITLE
Testing GraphQL Services?

### ISSUE THREAD

**Issue by robodude666** [moleculerjs/moleculer-apollo-server#59]
I'm curious how you'd test a GraphQL service. For example, take the [simple greeter](https://github.com/moleculerjs/moleculer-apollo-server/blob/1e496df/examples/simple/index.js#L39-L82) service.

Sure, you could certainly call the actions and pass in params, but that wouldn't test the graphql definitions. To test that, would you need to add the `ApolloService` mixin to your test broker and then use a graphql client? Or is there a simpler way?

**Comment by icebob** [comment]
I think you can test it with a simple `request` lib which sends the GraphQL query as a REST request.

**Comment by icebob** [comment]
I've just added some integration test: https://github.com/moleculerjs/moleculer-apollo-server/blob/master/test/integration/greeter.spec.js#L111
