### ISSUE TITLE
Should not call installSubscriptionHandlers when serverOptions.subscriptions is false

### ISSUE THREAD

**Issue by silvacpp** [moleculerjs/moleculer-apollo-server#64]
![image](https://user-images.githubusercontent.com/8548043/75062577-d5c37800-54c1-11ea-86d4-e42caebcbd80.png)
As shown in the apollo server options,  subscriptions can be false and if was,  installSubscriptionHandlers could not be called.
If called an exception is thrown 
![image](https://user-images.githubusercontent.com/8548043/75063144-0526b480-54c3-11ea-9e16-db9437ac048e.png)

**Comment by icebob** [comment]
Released in 0.3.1
