### ISSUE TITLE
UNABLE_COMPILE_GRAPHQL_SCHEMA Unknown type "Upload"

### ISSUE THREAD

**Issue by vora-bei** [moleculerjs/moleculer-apollo-server#66]
I try to enable upload, but  i have UNABLE_COMPILE_GRAPHQL_SCHEMA Unknown type "Upload" 
I set uploads: true

**Comment by vora-bei** [comment]
I tried to add Scalar Upload, but i had another error typeError: this.initSchema is not a function

**Comment by icebob** [comment]
Show a repro example.

**Comment by vora-bei** [comment]
It represents only 0.1.3
