### ISSUE TITLE
GraphQL Playground Polling Path Incorrect When routeOptions.path != '/graphql'

### ISSUE THREAD

**Issue by valeeum** [moleculerjs/moleculer-apollo-server#68]
When either routeOptions.path or a basePath is added to moleculer-web route, graphql playground does load but the polling that happens in the background continues to hit the default path, /graphql,  resulting in 404 error

![image](https://user-images.githubusercontent.com/1195356/76559174-e54c3600-645b-11ea-91f0-b39ec5bba600.png)

**Comment by icebob** [comment]
Why don't you change the path in playground as well?
![image](https://user-images.githubusercontent.com/306521/76688598-a6220e80-662e-11ea-9b74-3cd65e2979ef.png)

**Comment by valeeum** [comment]
wow i am embarrassed for two reasons.  you are right, I overlooked this and that did solve my issue.  second, i didn't realize i had profanities in my screenshot.  apparently i need to pay better attention to details.
