### ISSUE TITLE
Return ENUM in Action

### ISSUE THREAD

**Issue by Tautorn** [moleculerjs/moleculer-apollo-server#70]
Hi there.

I have a service and I need to return an enum in my action.

How can I make this return? Example:

```js

@Service({
    name: "xxx",

    mixins: [],

    collection: "xxx",

    settings: {
        graphql: {
            type: `
                enum Type {
                    FIRED
                }
            `,

            resolvers: {
               
            },
        },
    },

    dependencies: [],

    hooks: {
        after: {
            create: [
                "cleanCache",
            ],
        },
    },
})
```

I'm trying this:

```
class xxx extends Moleculer.Service {

@Action({
        cache: true,
        graphql: {
            query: "getTypes(): Type",
        },
    })
    public getTypes() {
        return Type
    }
}

export = xxx
```

Terminal error:
```
[Runner] Missing action handler on 'getTypes' action in 'xxx' service! ServiceSchemaError: Missing action handler on 'getTypes' action in 'xxx' service!
    at Object._createAction
```

**Comment by shawnmcknight** [comment]
You'll need an enumeration resolver to convert your internal representation of an enumeration to the GraphQL enumeration: https://www.apollographql.com/docs/graphql-tools/scalars/#internal-values.

Here's a small sample of one I have in a service to convert from TS enums to GraphQL enums:

```
settings: {
  graphql: {
    enum: [`
      enum CartLineFulfillmentMethod {
        none
        delivery
        customerPickup
        directShip
      }`
    ],
    resolvers: {
      CartLineFulfillmentMethod: {
        none: CartLineFulfillmentMethod.none,
        delivery: CartLineFulfillmentMethod.delivery,
        customerPickup: CartLineFulfillmentMethod.customerPickup,
        directShip: CartLineFulfillmentMethod.directShip,
    },
```

with TS enum:
```
enum CartLineFulfillmentMethod {
	none = '',
	delivery = 'D',
	customerPickup = 'P',
	directShip = 'M',
}
```

When GraphQL resolves the enumeration type, it will perform conversions from the internal to the external representation and vice versa.

**Comment by shawnmcknight** [comment]
Also, your action is returning something named `Type`, but I don't see that being assigned anywhere.  You need to still return a value.  The enumeration resolver will just map that value to the GraphQL enumeration.

**Comment by Tautorn** [comment]
Hi @shawnmcknight,

thank you for your answer. I did the changes in my service like your response and are working for me. 
Also, I've added a return to my `action`.

Thank you for the explanation,  are clear for me now.
