### ISSUE TITLE
How to upload a file?

### ISSUE THREAD

**Issue by ghosh-jaideep** [moleculerjs/moleculer-apollo-server#81]
Looking for a documentation which can guide me to the steps by which I can add the the functionality of file upload.

**Comment by shawnmcknight** [comment]
> Looking for a documentation which can guide me to the steps by which I can add the the functionality of file upload.

**Docs**:
https://github.com/moleculerjs/moleculer-apollo-server#file-uploads

**Example**:
https://github.com/moleculerjs/moleculer-apollo-server/blob/master/examples/upload/index.js
