### ISSUE TITLE
Run-time generated queries, mutations, types, etc...?

### ISSUE THREAD

**Issue by valeeum** [moleculerjs/moleculer-apollo-server#86]
Is it possible/recommended to create run-time generated queries, mutations, etc?   I have a need to let users create the interface to their api similar to GraphCMS.   Is there any graphql api downtime when calling invalidateGraphQLSchema + prepareGraphQLSchema when graphql is already running?

**Comment by shawnmcknight** [comment]
> Is it possible/recommended to create run-time generated queries, mutations, etc?   I have a need to let users create the interface to their api similar to GraphCMS.   Is there any graphql api downtime when calling invalidateGraphQLSchema + prepareGraphQLSchema when graphql is already running?  

When the schema is invalidated, the api remains responsive and will generate the GraphQL schema when the next request comes in. There's some possible latency to that, but it should not result in downtime.

**Comment by valeeum** [comment]
thank you for the insight!
